# Generated by Django 4.1.2 on 2022-11-09 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Айпи адрес просмотра",
                "verbose_name_plural": "Айпи адреса просмотров",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="views",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
