# Generated by Django 4.1.2 on 2022-11-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_api", "0002_alter_publisher_options_alter_publisher_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="stars",
            field=models.CharField(
                choices=[(1, "*"), (2, "**"), (3, "***"), (4, "****"), (5, "*****")],
                default=0.0,
                max_length=10,
            ),
        ),
    ]
