# Generated by Django 4.1.2 on 2022-11-04 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media_api", "0003_alter_rating_stars"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="stars",
        ),
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="media_api.rating",
            ),
        ),
    ]
