favorite_genre = (
    ("Sandbox", "Sandbox"),
    ("RTS", "RTS)"),
    ("FPS", "FPS"),
    ("MOBA", "MOBA"),
    ("RPG", "RPG"),
    ("MMORPG", "MMORPG"),
    ("MMOFPS", "MMOFPS"),
    ("Simulator", "Simulator"),
    ("Battle_royale", "Battle_royale"),
    ("Survival", "Survival"),
    ("Horror", "Horror"),
    ("Puzzles", "Puzzles"),
    ("Platformer", "Platformer"),
    ("Adventure", "Adventure"),
    ("Sport", "Sport"),
)
